language: node_js
node_js:
  - "4.2"
after_script:
    - npm run coverage
notifications:
  email:
    recipients:
      - lihaitao03@baidu.com
      - hanbingfeng@baidu.com
      - wangyi25@baidu.com
    on_success: change
    on_failure: always